### ISSUE TITLE
Large file size

### ISSUE THREAD

**Issue by nil3190** [FKLC/Torrent-To-Google-Drive-Downloader#1]
Hello sir, large filesize around 4 gb was not able to upload to drive..  i was getting progress complete message..but in the folder of drive the was no file.

**Comment by FKLC** [comment]
Are you sure that you mount Google Drive? When I was using this notebook even while the download process not completed the files are shown on Google Drive.

**Comment by nil3190** [comment]
Yes.. i mount Google drive. Also  i tried with 300mb torrent file which was successfully uploaded to drive

**Comment by FKLC** [comment]
This is weird but i don't know how to fix it, sorry.

**Comment by nil3190** [comment]
Ok. Anyways.thank you for the nice work.  Keep it up.

**Comment by FKLC** [comment]
I'll be inform you if one day I'll figure out what is the problem.
