### ISSUE TITLE
Runtime keeps getting disconnected every few minutes

### ISSUE THREAD

**Issue by feecof** [FKLC/Torrent-To-Google-Drive-Downloader#14]
So I have been facing this issue every single time whenever I run the notebook in(GPU acceleration). Runtime keeps getting disconnected. When I don't use any acceleration I don't get the runtime disconnected error.

**Comment by FKLC** [comment]
Have you ever ran a notebook over 12hours in one session?

**Comment by feecof** [comment]
Nope, my notebook sessions are < 1hr.
Can you try to download a large torrent file like >30gb and see if your runtime gets disconnected too? Maybe @pentaly7 can?

**Comment by FKLC** [comment]
I tried too and as you said after a while it disconnected me too but not every few minutes. Sorry but I can't help you with that.

**Comment by xPentaly** [comment]
change google account for run google colab notebook,

**Comment by FKLC** [comment]
If your problem solved please close the issue or I'll close issue after 10 days

**Comment by feecof** [comment]
@FKLC oh sorry forgot to close this issue. But ive been using transmission cli on colab and its been a lot more stable, also when the runtime does get disconnected the partial downloaded torrent doesnt get wiped away so i can resume from lost progress. You should test with transmission cli too. libtorrent doesnt seem very stable and if the runtime disconnects whole torrent gets deleted.
