### ISSUE TITLE
python 3 google compute engine backend disk is full

### ISSUE THREAD

**Issue by GajarubanSaravanan** [FKLC/Torrent-To-Google-Drive-Downloader#2]
how to slove it i can't locate the old downladed files that are stored on the python 3 google compute engine backend disk.

**Comment by FKLC** [comment]
I can't say that I really understand what you meant to but if you are asking for how to delete old files you have to notice that this notebook streams files to Google Drive. It is not keeping files on the notebook session. If you are running out of free space in your notebook session because of old usages you can basically terminate your session through Runtime > Manage Sessions > Current Session > Terminate. But in normal terms this shouldn't be happen this might be caused because you are continuing to use old notebook which is already full of disk space.

**Comment by GajarubanSaravanan** [comment]
Thanks for the tip, but how can I download a file more than 50gb because when I was downloading the store is becoming full and it says delete some data to free the space and when the store is full it’s stopped downloading and saying store is full

Sent from Mail for Windows 10

**Comment by FKLC** [comment]
Can you run and check the output of `!df -h` command?
If you are running out of space in Google Drive you should see something like:
```
Filesystem      Size  Used Avail Use% Mounted on
drive            15G   15G  583M  97% /content/drive
```
If you are running out of space in Google Drive you have to purchase other plans but if you are actually somehow running out of space in notebook session this is weird and I don't know how to fix it.

**Comment by GajarubanSaravanan** [comment]
I have 100gb student pack and I only filled 22 gb and I’m trying to download a 45gb file
On the top right there is an additional connection option in that you have selected 
Connected to hosted runtime. In that one when I download some ting the store is getting filled the start limit for me is 23gb/48.97 why is that and it says waiting for python 3 google compute engine backend to finish its current execution. Can you please send your email to me so I can send a image about it. And thank you for replying me..
Sent from Mail for Windows 10

**Comment by FKLC** [comment]
You can actually attach files to comments in github but if you are really like to mail me it is me@fklc.dev

**Comment by GajarubanSaravanan** [comment]
![Screenshot (140)](https://user-images.githubusercontent.com/39818976/57547052-6ab61400-737b-11e9-9ffc-96acde13f932.png)
It's before download 22/49gb and
![Screenshot (141)](https://user-images.githubusercontent.com/39818976/57547091-79043000-737b-11e9-8a68-490c86813f0b.png)
this is when downloading, the store capacity increases with the download capacity
so how can i download more than 40gb file can i add some space by deleting stuff or by increasing the store space so how to do it

**Comment by FKLC** [comment]
Mailing History:

**FKLC:**
Colab maintainers says it is not possible to change resources of notebook so basically is seems to be impossible.
https://github.com/googlecolab/colabtools/issues/253

---

**GajarubanSaravanan**


Can you find me a way to upload hug file to google drive like 50+gb torrent files, please

---

**FKLC:**
No, basically this is impossible to achieve sorry.

---

**GajarubanSaravanan**
Anyways thanks for the support and help bro, thank you soo much

---

**FKLC:**
Anytime!
