### ISSUE TITLE
Use magnet or link to torrent instead of uploading

### ISSUE THREAD

**Issue by pranjalja1n** [FKLC/Torrent-To-Google-Drive-Downloader#3]
Hey man,

First of all thanks for this code, it helped me download a torrent for a dataset I was not able to download myself.

I wanted to ask you, that in your code it is necessary to upload a .torrent file first and then download it. Can we modify this code to accept Magnet links directly or get a torrent file from a link instead of uploading a .torrent file ourselves?

**Comment by FKLC** [comment]
It uses libtorrent library and according to this [stackoverflow question](https://stackoverflow.com/a/6053350/7957705) replacing these lines:
```py
info = lt.torrent_info(list(uploaded.keys())[0])
h = ses.add_torrent({"ti": info, "save_path": "/content/drive/My Drive/Torrent"})
```
With this:
```py
params = { 'save_path': '/content/drive/My Drive/Torrent'}
link = "your_magnet_link"
h = lt.add_magnet_uri(ses, link, params)
```
Should download magnet links. (Because I've sold my pc i stopped developing things so i haven't had a chance to try it but i think it should work if not let me now, if works close the issue)

**Comment by pranjalja1n** [comment]
I tried this, It worked cause my torrent files are being checked and the % counter has started rising.

I will close the issue just after I ask you this: Your readme.md states that this is useless, can you explain why do you think this is useless? I tried transmission-cli and that didn't work for me, are there other torrent clients for CLI that work in Google Colab?

**Comment by FKLC** [comment]
Because you know most torrent clients allows you to select which files to download and loading files to google drive is useless. But actually in your case (downloading dataset to google colab) is might be useful because of downloading torrents in colab and not streaming them to drive.
