### ISSUE TITLE
disk is full

### ISSUE THREAD

**Issue by xPentaly** [FKLC/Torrent-To-Google-Drive-Downloader#5]
i try to download 33gb file, but when download progress 48% it says drive is full. it seems this method cant download more than 20gb

**Comment by FKLC** [comment]
yeah looking back #2 and #1 issues google colab also counts mounted drive storage as its own storage. and i don't know how to fix it sorry :(

**Comment by kasvith** [comment]
Go to Runtime -> Change Runtime and give GPU as the Hardware Accelerator.
You will get around 384GB to download any torrent you want

**Comment by xPentaly** [comment]
@kasvith thank you, i can download bigger torrent file now.

**Comment by kasvith** [comment]
😃

**Comment by muhammedfurkan** [comment]
When this feature is activated, can we download with our own internet download speed?  Or as before?

**Comment by vijeshpillai** [comment]
Magnet link code not working
