### ISSUE TITLE
cannot download files greater than 15gb

### ISSUE THREAD

**Issue by feecof** [FKLC/Torrent-To-Google-Drive-Downloader#9]
everytime i add a torrent greater than 15 gb it downloads all the way but in my drive it shows a size of 0B. on rechecking the torrent everything seems fine. is it because i have a free google drive account(15gb storage)?

**Comment by FKLC** [comment]
Yes you can't download files bigger than your Google Drive size but I tried downloading file bigger than 15GB I also use free version of GDrive but only some of the files were not existed. This is weird I'm sorry but I actually don't know how to fix it.

**Comment by FKLC** [comment]
I've tried again and when my drive full it stopped for a while and resumed after that. But I can see downloaded files in my drive. Maybe try terminating your session and downloading again. Sorry for taking your time.

To terminate session: Runtime > Manage Sessions > Terminate Session

**Comment by xPentaly** [comment]
you need an unlimited gdrive account or an edu account for unlimited gdrive storage.

**Comment by FKLC** [comment]
@rhyzq Yes this is right but the problem is he mentions his drive is empty. This isn't what should've happened. I tried downloading bigger torrent than my GDrive limit even it stopped downloaded files were still there

**Comment by xPentaly** [comment]
@FKLC @Grainlord  it happens for me too sometimes, i just restart all runtime(runtime>reset all runtimes)  then start that torrent again and fastresume will check the file, or u can just delete the 0b file then redownload the torrent.

**Comment by FKLC** [comment]
@rhyzq thank you for answer. so @Grainlord can you please try @rhyzq method first then my method and inform us so i can put this question to FAQ.

**Comment by feecof** [comment]
@FKLC tried both the methods, any file greater than 15gb doesnt show in the drive.

**Comment by xPentaly** [comment]
try to download using unlimited gdrive account, u can google how to make it or buy one.

**Comment by xPentaly** [comment]
this is the prove that u can download a file more than 15gb using google colab but i am using google drive unlimited account

![image](https://user-images.githubusercontent.com/18513036/63492379-8f299c80-c4e3-11e9-844d-1cd457f15f51.png)

**Comment by feecof** [comment]
@FKLC @rhyzq Got a .edu acoount now. Having no issues, thanks. is it possible to queue more than 1 magnet link? there is a website torrenttodrive.com (goes by name avocado) i think it works on the same principle but allows queuing of torrents, which is quite helpful.

But what if you can make it so that instead of downloading torrents to my own cloud it downloads it to a specific .edu account which is monitored by a script which deletes data older than 2 days or something? So like a free unlimited cloud for everyone to access. idk its just a thought.

**Comment by FKLC** [comment]
Queueing is not available but you can download in parallel. Just run adding magnet link cell as many times you want

Sorry but we can't delete files older than 2 days because it needs to be checked everyday and you can't hold Colab servers online.

If all of your questions are answered. Please close the issue.

**Comment by feecof** [comment]
ok, thanks
